import './layout.css';
import './text.css';

const defaultTheme = {
	blockCursor: 'ui-text-editor__block-cursor',
	hashtag: 'ui-text-editor__hashtag',
	heading: {
		h1: 'ui-text-editor__h1',
		h2: 'ui-text-editor__h2',
		h3: 'ui-text-editor__h3',
		h4: 'ui-text-editor__h4',
		h5: 'ui-text-editor__h5',
		h6: 'ui-text-editor__h6',
	},
	image: 'ui-text-editor__image',
	indent: 'ui-text-editor__indent',
	link: 'ui-text-editor__link',
	list: {
		listitem: 'ui-text-editor__listItem',
		listitemChecked: 'ui-text-editor__listItemChecked',
		listitemUnchecked: 'ui-text-editor__listItemUnchecked',
		nested: {
			listitem: 'ui-text-editor__nestedListItem',
		},
		olDepth: [
			'ui-text-editor__ol1',
			'ui-text-editor__ol2',
			'ui-text-editor__ol3',
			'ui-text-editor__ol4',
			'ui-text-editor__ol5',
		],
		ul: 'ui-text-editor__ul',
	},
	ltr: 'ui-text-editor__ltr',
	paragraph: 'ui-text-editor__paragraph',
	quote: 'ui-text-editor__quote',
	rtl: 'ui-text-editor__rtl',
	text: {
		bold: 'ui-text-editor__text-bold',
		code: 'ui-text-editor__text-code',
		italic: 'ui-text-editor__text-italic',
		strikethrough: 'ui-text-editor__text-strikethrough',
		subscript: 'ui-text-editor__text-subscript',
		superscript: 'ui-text-editor__text-superscript',
		underline: 'ui-text-editor__text-underline',
		underlineStrikethrough: 'ui-text-editor__text-underline-strikethrough',
	},
	mention: 'ui-text-editor__mention',
	code: 'ui-text-editor__code',
	spoiler: {
		container: 'ui-text-editor__spoiler',
		title: 'ui-text-editor__spoiler-title',
		content: 'ui-text-editor__spoiler-content',
	},
	smiley: 'ui-text-editor__smiley',
	codeHighlight: {
		operator: 'ui-text-editor__token-operator',
		punctuation: 'ui-text-editor__token-punctuation',
		comment: 'ui-text-editor__token-comment',
		word: 'ui-text-editor__token-word',
		keyword: 'ui-text-editor__token-keyword',
		boolean: 'ui-text-editor__token-boolean',
		regex: 'ui-text-editor__token-regex',
		string: 'ui-text-editor__token-string',
		number: 'ui-text-editor__token-number',
		semicolon: 'ui-text-editor__token-semicolon',
		bracket: 'ui-text-editor__token-bracket',
		brace: 'ui-text-editor__token-brace',
		parentheses: 'ui-text-editor__token-parentheses',
	},
	video: 'ui-text-editor__video',
	table: 'ui-text-editor__table',
	tableRow: 'ui-text-editor__table-row',
	tableCell: 'ui-text-editor__table-cell',
	tableCellHeader: 'ui-text-editor__table-cell-header',
	tableSelection: 'ui-text-editor__table-selection',
	file: {
		file: 'ui-text-editor__file',
		image: 'ui-text-editor__file-image',
		video: 'ui-text-editor__file-video',
	},
};

export default defaultTheme;
